function unlock(elm, targetGrid) {
//    jQuery("#itemGrid").jqGrid('showCol', ["actions", "cb"]);
//    $('#addRowBtn').removeClass('ui-state-disabled');
    elm.$el.addClass('editing');
    $('.value input[type="text"]').prop("disabled", false);
    $('.value input[type="checkbox"]').prop("disabled", false);
    $('.value select').prop("disabled",false);
    $('#generalNote').prop("disabled", false);
    $(".lockBtns").hide();
    $(".unlockBtns").show();
//    var jqGridWrapperId = "#gbox_" + targetGrid.attr('id') //here be dragons, this is     generated by jqGrid.
//    targetGrid.setGridWidth($(jqGridWrapperId).parent().width()-1); //perhaps add padding calculation here?
}

function lock(elm, targetGrid) {
//    jQuery("#itemGrid").jqGrid('hideCol', ["actions", "cb"]);
//    $('#addRowBtn').addClass('ui-state-disabled');;
    elm.$el.removeClass('editing');
    $('.value input[type="text"]').prop("disabled", true);
    $('.value input[type="checkbox"]').prop("disabled", true);
    $('.value select').prop("disabled", true);
    $('#generalNote').prop("disabled", true);
    $(".lockBtns").show();
    $(".unlockBtns").hide();
//    var jqGridWrapperId = "#gbox_" + targetGrid.attr('id') //here be dragons, this is     generated by jqGrid.
//    targetGrid.setGridWidth($(jqGridWrapperId).parent().width()-1); //perhaps add padding calculation here?
}

function unlockGrid(targetGrid, addBtn) {
    targetGrid.jqGrid('showCol', ["actions", "cb"]);
    addBtn.removeClass('ui-state-disabled');
    var jqGridWrapperId = "#gbox_" + targetGrid.attr('id') //here be dragons, this is     generated by jqGrid.
    targetGrid.setGridWidth($(jqGridWrapperId).parent().width()-1); //perhaps add padding calculation here?
}

function lockGrid(targetGrid, addBtn) {
    targetGrid.jqGrid('hideCol', ["actions", "cb"]);
    addBtn.addClass('ui-state-disabled');
    var jqGridWrapperId = "#gbox_" + targetGrid.attr('id') //here be dragons, this is     generated by jqGrid.
    targetGrid.setGridWidth($(jqGridWrapperId).parent().width()-2); //perhaps add padding calculation here?
}